<?xml version="1.0" encoding="UTF-8"?>
<office:document-meta xmlns:grddl="http://www.w3.org/2003/g/data-view#"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:ooo="http://openoffice.org/2004/office"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0"
    xmlns:smil="urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
    xmlns:anim="urn:oasis:names:tc:opendocument:xmlns:animation:1.0"
    xmlns:officeooo="http://openoffice.org/2009/office" office:version="1.3">
    <office:meta>
        <meta:generator>SpmImageTycoon.jl</meta:generator>
        <dc:description>Generated by SpmImageTycoon.jl</dc:description>
        <meta:keyword>{{ keywords }}</meta:keyword>
        <dc:subject></dc:subject>
        <dc:title>{{ title }}</dc:title>
    </office:meta>
</office:document-meta>